### ISSUE TITLE
Erro 2168-0002 ao abrir o CNX

### ISSUE THREAD

**Issue by joaopedrors9** [AMSNX/cnx-updater#11]
Estou com o erro 2168-0002 quando abro o CNX, ele tá a tela de erro e é preciso reiniciar o switch.

se alguém conseguir me ajudar, agradeço.

**Comment by joaopedrors9** [comment]
Anexei a foto do erro e o log
![Imagem do WhatsApp de 2023-11-25 à(s) 22 40 00_6c07c47b](https://github.com/AMSNX/cnx-updater/assets/80704640/ad3b0439-3115-42f7-8de4-1b31e6641a01)
[01700962535_010000000000100d.log](https://github.com/AMSNX/cnx-updater/files/13465688/01700962535_010000000000100d.log)

Ao baixar a versão 3.1.0 ele abre e solicita a atualização, porem quando atualiza ocorre o erro novamente

**Comment by AMSNX** [comment]
baixem a versão mais atual aqui no github e extrai no sd que vai funcionar, lembre se estarem sempre conectado ante de abrir o app
