### ISSUE TITLE
Erro 2168-0002

### ISSUE THREAD

**Issue by Sandrochemist** [AMSNX/cnx-updater#14]
O cnx updater apresenta o erro 2168-0002 logo após baixar a tradução do jogo final fantasy VII.

**Comment by joaopedrors9** [comment]
meu caso também é parecido, instalei algumas traduções, porem a que mais lembro foi a de FF VII

**Comment by AMSNX** [comment]
era um erro no hash do arquivo que já foi corrigido, obrigado pelo feedback
