### ISSUE TITLE
Request - old loader.kip and sys-clk modded

### ISSUE THREAD

**Issue by sauliiin** [AMSNX/cnx-updater#16]
Bom dia, amigo! Espero que esteja tudo bem.

Atualizei para CNX 17.0.1-4, mas estou utilizando o loader.kip da versão CNX 17.0.1-3. Em alguns jogos, o simples OC da RAM já é suficiente para conseguir 30fps estáveis. Alan Wake, por exemplo, que é um jogo muito mal otimizado, zerei liso com as configd do antigo loader.kip.

Apesar de eu ter conseguido fazer o oveclock na RAM acima de 1600, a maioria dos usuários não consegue, por isso a sugestão.

Se possível, gostaria que incluísse mais opções de overclock, em especial para a RAM. Se me permite, sugiro como valores máximos os safes disponíveis aki: https://github.com/rashevskyv/sys-clk-OC.

Outra sugestão e me desculpe pela intromissão. Apesar da vantagem ser pequena, esse mod do sys-clk (https://github.com/jope82/sys-clk-uncapped-gpu-and-other-extras/releases/tag/2.0.0_a) roda melhor que o original, especialmente nos loads.

Não tenho conhecimento em C++, mas me viro em C. Caso possa ajudar e esteja a meu alcance, estou à disposição.

**Comment by AMSNX** [comment]
vou ver se retorno com o um outro custom kip com a possibilidade de Clocks mariores. Dai faço uma opção extra no MORE CONFIGS igual deixem o boot com CFW na SYSNAND
