### ISSUE TITLE
CNX não é compativel com versão do athmosphere

### ISSUE THREAD

**Issue by satodu** [AMSNX/cnx-updater#20]
Boa tarde,

Estoou usando e começou a aparecer essa mensagem de que não é compativel com a versão do athmosphere, mas verifiquei e atulizei está na ultima versão.

**Comment by satodu** [comment]
Complementando aparece a mensagem: 

"Para aproveitar todas as comodidaes e funcionalidades que este homebrew proporciona ...."

**Comment by cosmenasc** [comment]
Da um erro: Aviso Importante - O CNX não é compatível com o pacote Atmospere atualmente em uso! ... O q fazer?

**Comment by XxRickzera** [comment]
Estou com o mesmo problema, atualizado pra versão 3.1.3. 
Aviso Importante: O CNX não é compatível com o pacote Atmospère atualmente em uso!

**Comment by XxRickzera** [comment]
Descobri, esse problema é devido utilizar uma versão modificada do CNX, é necessário instalar a versão oficial (original), para que funcione adequadamente.
Regularizei seguindo as orientações desse vídeo e está perfeito agora.
https://www.youtube.com/watch?v=H-SmPeYio1s

**Comment by nicolasandreas** [comment]
Isso ocorre por estar usando o pacote de desbloqueio diferente ou modificado do GNX ou CNX, tem q estar usando o original, para corrigir só fazendo a modificação manual, pode seguir esse tutorial: https://youtu.be/09pT6icEtg0
