### ISSUE TITLE
Problemas ao baixar traduções e modificações

### ISSUE THREAD

**Issue by eliberatori** [AMSNX/cnx-updater#24]
Caros,
Tentei baixar tradução de Zelda (TOTK) e modificação para N64 Online e não consegui. Ao final, apareceu a mensagem em anexo, informando a ocorrência de "erro 509". Fiz diversas tentativas, mas o problema persistiu. Abraços!
![WhatsApp Image 2024-04-27 at 19 59 08](https://github.com/AMSNX/cnx-updater/assets/168311484/ddd7e110-3ea9-4a2a-a141-9870df05f94b)

**Comment by Maykoncorreia** [comment]
Também tenho tido o mesmo problema ao tentar baixar a modificação do SNES Online Roms By Papero (620mb). As outras de SNES eu consigo baixar, mas os jogos não iniciam mesmo após eu atualizar a firmware e migrar do CNX para o GNX.

**Comment by viBetra** [comment]
Tive o mesmo problema com a tradução do Yu Gi Oh

**Comment by tiago3030** [comment]
Estou tento o mesmo problema, na verdade, um pouco pior. Eu consegui baixar a modificação do SNES Online Roms By Papero (620mb), no entanto, após a instalação, não funcionou no emulador, os jogos não abriam. Quando fui no CNX pra desinstalar o mod, aparecia a opção para baixar e não para apagar. Estou sem as roms modificadas e sem acesso às roms do emulador "original". Alguém sabe como resolver isso?

**Comment by Eduardolinden** [comment]
Estou com o mesmo problema,  não consigo baixar quase nenhuma tradução

**Comment by rafael23mota** [comment]
Tive esse mesmo problema ao baixar, pelo CNX, a versão SNES Online Roms By Papero (620mb).
Mesmo desinstalando e instalando a versão normal do TINFOIL, os jogos não rodavam.
Consegui resolver esse problema da seguinte maneira:
Acessei o DBI INSTALLER, entrei em CONTENTS e apaguei a pasta do SUPER NINTENDO inteira.
Depois baixei novamente a versão do Super Nitnendo pelo Tinfoil e deu certo. Os jogos voltaram a rodar.
Contudo, não consigo baixar nenhum pack de SNES pelo CNX, pois contina a dar o erro 509. Mas, pelo menos, os jogos voltaram a rodar.
