### ISSUE TITLE
Error: 509

### ISSUE THREAD

**Issue by tiago3030** [AMSNX/cnx-updater#25]
PT-BR
Ontem tentei baixar um pack de ROMs do snes online, no entato, não consegui baixar pois o CNX acusou o erro 509, congelando o console em seguida. Hoje eu consegui fazer o download, porém, não funcionou no emulador. Após constatar isso, fui ao CNX para desligar o MOD, entretanto, não aparece essa opção no CNX, é como se eu estivesse sem o mod no switch, sendo que, na verdade, o mod está lá, só não consigo apagá-lo. Isso está me impedindo de usar o emulador, pois esse mod congela o console inteiro. Alguém sabe como posso apagar esse mod?

EN-US
Yesterday I tried to download a snes ROM pack online, however, I was unable to download it because CNX reported error 509, freezing the console afterwards. Today I managed to download it, however, it didn't work on the emulator. After realizing this, I went to CNX to turn off the MOD, however, this option does not appear on CNX, it is as if I were without the mod on the switch, whereas, in fact, the mod is there, I just cannot delete it. This is preventing me from using the emulator as this mod freezes the entire console. Does anyone know how I can delete this mod?

**Comment by DanielSvoboda** [comment]
Tive o mesmo problema, isso ficou um textão, mas ta ai né, consegui resolver: 
Resumido: "Estava usando o GNX, instalei o CNX e deu certo.

Baixei a modificação do SNES Online Roms, até abria o emulador, porem alguns jogos modificados não estavam funcionando. Notei que estava na versão errada 3.8. Atualizei para 3.9 (que é exigido) e depois não consegui mais baixar os 'mod', erro 503 e 509. Apertava o botão pra baixar mas dava erro, eu não tinha removido o mod antes de atualizar o snes, então não deveria mostrar o botão pra baixar e sim de remover.
Reinstalei o 'snes' pelo dbi mas acontece mesma coisa, aparece a tela de baixar em 0% e apresenta o erro, as vezes não dava erro e só ia para o finalizado mas sem instalar.
Notei que estava usando GNX e não CNX, então instalei o CNX que tem o patch 'SNES Online - Full Unlock', e antes de fazer a 'instalação limpa' salve alguns mods da pasta atmosphere/content, menos a pasta do snes, pq lá tinha alguns resquícios. Consegui instalar o mod, apareceu a estrela de instalado e rodou as rom modificadas em pt-br no snes.

**Comment by tiago3030** [comment]
Olá, Daniel!
Valeu pelo seu relato. Você pode me passar o arquivo do CNX que tem o patch 'SNES online - Full unlock'? Não consegui encontrar esse arquivo pesquisando pela internet.

**Comment by DanielSvoboda** [comment]
Você não precisa procurar na internet, você já esta no local onde os arquivos estão, é esse usuário que tem os arquivos do CNX e o CNX_updater. É só baixar o ultimo arquivo de release, é nesse link: https://github.com/AMSNX/CNX/releases
Dentro do zip [CNX.18.0.1-1.zip](https://github.com/AMSNX/CNX/releases/download/18.0.1-1/CNX.18.0.1-1.zip) você vai ate a pasta "\atmosphere\exefs_patches\SNES Online - Full Unlock" mas você não precisa baixar manualmente, da pra atualizar direto pelo switch, na verdade não testei só copiando isso, no meu caso eu tinha o cnx-updater porem ele estava lá pq eu tinha o pacote do gnx, então não estava instalado esse unlock, se for o teu caso e vc quer trocar de pacote de desbloqueio: Eu fui dentro do switch e abri o cnx-updater e baixei o pacote atmosphere do CNX. E quando faz a instalação limpa ele apaga os mod/traduções, eu abri o cartão pelo dbi e salvei as pastas dos mod de tradução de alguns jogos que eu mesmo tinha instalado pelo pc, mas isso é opcional, pq eu não tinha mais os arquivo pra instalar no pc, então peguei direto do cartão, e depois colei la devolta, só dos jogos que eu coloquei mod, era traduções de alguns jogos.

**Comment by rafael23mota** [comment]
Tive esse mesmo problema ao baixar a, pelo CNX, a versão SNES Online Roms By Papero (620mb).
Mesmo desinstalando e instalando a versão normal do TINFOIL, os jogos não rodavam.
Consegui resolver esse problema da seguinte maneira:
Acessei o DBI INSTALLER, entrei em CONTENTS e apaguei a pasta do SUPER NINTENDO inteira.
Depois baixei novamente a versão do Super Nitnendo pelo Tinfoil e deu certo. Os jogos voltaram a rodar.
Contudo, não consigo baixar nenhum pack de SNES pelo CNX, pois contina a dar o erro 509. Mas, pelo menos, os jogos voltaram a rodar.
