### ISSUE TITLE
Erro 503

### ISSUE THREAD

**Issue by guimape** [AMSNX/cnx-updater#6]
Tinha feito o Update do homebrew por ele mesmo, aí ficou dando esse erro 503, já apaguei e reinstalei pelo computador o homebrew mas continuo com o mesmo erro, podem me ajuda ?

**Comment by rodri1991** [comment]
Mesmo problema aqui
![20230917_135129](https://github.com/AMSNX/cnx-updater/assets/145304650/83da18c6-1930-4f06-9d94-1701ee37ccba)

**Comment by rodri1991** [comment]
Resolvido! 👍🏼
![IMG_3372](https://github.com/AMSNX/cnx-updater/assets/145304650/e75784c4-c50f-4260-a2f8-5276cc25f25f)

**Comment by guimape** [comment]
Aqui voltou tbm
